### PR TITLE
#507 Parameter finite states

### PR DESCRIPTION
**Pull request by cozminvelciu**
### Prerequisites

- [x] I have written a descriptive pull-request title
- [x] I have verified that there are no overlapping [pull-requests](https://github.com/RHEAGROUP/CDP4-IME-Community-Edition/pulls) open
- [ ] I have verified that I am following the CDP4-IME [code style guidelines](https://raw.githubusercontent.com/RHEAGROUP/CDP4-IME-Community-Edition/master/.github/CONTRIBUTING.md)
- [ ] I have provided test coverage for my change (where applicable)

### Description
Data source parameter finite states handling:
* one row per parameter per state + one (optional row) for all non-state dependent parameters

### CODE REVIEW

**Comment by cozminvelciu** [comment]
> 
> 
> I think we should stick with this way for now, but with some additions:
> 
> Add an interface
> ` public interface IReportingDataSourceParameter<T> { T GetValue(); }`
> Let ReportingDataSourceParameter implement this:
> ` public abstract class ReportingDataSourceParameter<T, TType> : ReportingDataSourceColumn<T>, IReportingDataSourceParameter<TType> where T : ReportingDataSourceRow, new()`
> Create a DoubleReportingParameter that derives from `ReportingDataSourceParameter<T, double>` Create a StringReportingParameter that derives from `ReportingDataSourceParameter<T, string>`
> 
> We can use those in reports the way we are used to.

Yes, agreed. This seems like the best approach going forward.

**Comment by lxatrhea** [comment]
OK, let’s doo it like this.
Moving the DefinedShortNameAttribute to property level can then be done at a later stage.

**Comment by cozminvelciu** [comment]
Quite possibly no longer relevant as based on the discussion from 7 August with @lxatrhea the implementation needs to be changed to have the states as columns, now rows.

**Comment by cozminvelciu** [comment]
Closing as obsolete. After the discussions here the parameter finite states were added as columns in #552.

**Pull request closed without merging**
