### PR TITLE
#727 Fix multiple issues with saving manually filled values

### PR DESCRIPTION
**Pull request by cozminvelciu**
### Description
Of particular note is the change in the last commit, which was caused by a problem in the way CustomXMLParts were handled in `CDP4OfficeInfrastructure\OfficeDal\CustomOfficeDataDal.cs`.

⚠️ To be reviewed strictly after #731.

### CODE REVIEW

**Comment by cozminvelciu** [comment]
To be reviewed strictly after #731.

**Review by alexatrhea — APPROVED** [review]

**Review by alexatrhea — APPROVED** [review]

**Comment by alexatrhea** [comment]
You can merge this.

**Comment by alexatrhea** [comment]
> You can merge this.

Or I might have to do it for you due to QG fail, just let me know. From my side it is ready.

**Comment by cozminvelciu** [comment]
> > You can merge this.
> 
> Or I might have to do it for you due to QG fail, just let me know. From my side it is ready.

Yes, if you can please do it. I can't due to the fact that touching any file results in Sonar considering it's whole contents as part of the coverage for this pull request, instead of only looking at delta in coverage.

**Pull request merged**
